name = "NQCDInterfaceASE"
uuid = "4606675f-2246-4a0b-99d5-75b910de637b"
authors = ["Alexander Spears <alexander.spears@warwick.ac.uk> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
